apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice04
  labels:
    app: configservice04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice04
  template:
    metadata:
      labels:
        app: configservice04
    spec:
      containers:
        - name: configservice04
          image: 636090713215.dkr.ecr.us-east-1.amazonaws.com/configservice02:1.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080